### ISSUE TITLE
webview.loadUrl的时候为什么会跳转到默认浏览器

### ISSUE THREAD

**Issue by wangxp423** [wendux/DSBridge-Android#107]
JS调本地方法，js传过来一个url然后 用DWebview.loadUrl跳转url的时候，发现调起了手机自带默认的浏览器来记载传入的url。什么会这样，不应该的啊。

**Comment by wangyongpenga** [comment]
问题解决了吗？

**Comment by wangyongpenga** [comment]
dwebView.setWebViewClient(new WebViewClient() {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                view.loadUrl(url);
                return true;
            }
        });
