### ISSUE TITLE
默认的demo，x5未生效？

### ISSUE THREAD

**Issue by ColinSimple** [wendux/DSBridge-Android#111]
把默认的loadUrl换成 http://soft.imtt.qq.com/browser/tes/feedback.html   试了下。发现x5没生效。

注：显示000000表示加载的是系统内核，显示大于零的数字表示加载了x5内核（该数字是x5内核版本号）

**Comment by ColinSimple** [comment]
已经解决了。示例main下增加了 jniLibs 目录就可以了。

**Comment by Yinllo** [comment]
没用呀
