### ISSUE TITLE
Android 4.4.4  error

### ISSUE THREAD

**Issue by zy841336855** [wendux/DSBridge-Android#13]
09-01 10:59:33.932 4498-4498/com.hzty.rysj.leyou W/System.err: java.lang.NoClassDefFoundError: android.support.v7.widget.AppCompatDrawableManager$ColorFilterLruCache
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.support.v7.widget.AppCompatDrawableManager.<clinit>(SourceFile:103)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(Unknown Source)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.support.v7.app.AppCompatDelegateImplBase.<init>(Unknown Source)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.support.v7.app.AppCompatDelegateImplV9.<init>(Unknown Source)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.support.v7.app.AppCompatDelegateImplV11.<init>(Unknown Source)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.support.v7.app.AppCompatDelegateImplV14.<init>(Unknown Source)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.support.v7.app.AppCompatDelegate.create(Unknown Source)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.support.v7.app.AppCompatDelegate.create(Unknown Source)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.support.v7.app.AppCompatDialog.getDelegate(SourceFile:156)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.support.v7.app.AppCompatDialog.<init>(SourceFile:52)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.support.v7.app.AlertDialog.<init>(SourceFile:98)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.support.v7.app.AlertDialog$Builder.create(Unknown Source)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at wendu.dsbridge.DWebView$2.onJsAlert(SourceFile:318)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.handleJsAlert(WebViewContentsClientAdapter.java:612)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at com.android.org.chromium.android_webview.AwContentsClientBridge.handleJsAlert(AwContentsClientBridge.java:72)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.os.Looper.loop(Looper.java:136)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5103)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
09-01 10:59:33.936 4498-4498/com.hzty.rysj.leyou W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by wendux** [comment]
请补充异常场景
