### ISSUE TITLE
setJavaScriptInterface（）方法

### ISSUE THREAD

**Issue by XingshengLiu** [wendux/DSBridge-Android#14]
在调用的地方，这个只能set一个类是吧？我发现后边set的类，反射找方法的时候，都会在首次调用成功那个方法所在类中去找，写在其他类中的就找不到方法了

**Comment by wendux** [comment]
set方法后面的会覆盖前面的，只能设置一个

**Comment by XingshengLiu** [comment]
这样如果需要提供给H5的方法比较多，方法看起来就会很混乱了，有什么方法可以设置多个吗？

**Comment by wendux** [comment]
3.0之后支持命名空间，可以设置多个多个，请参考 #14
