### ISSUE TITLE
android webview里面 dsBridge报 dsBridge is not defined

### ISSUE THREAD

**Issue by EHONGYH** [wendux/DSBridge-Android#16]
操作如下，进入a页面dsBridge 能获得值，点击a链接跳转到b页面，然后在b页面返回到a页面时报 dsBridge is not defined。

**Comment by wendux** [comment]
b是怎么返回到a的？

**Comment by wendux** [comment]
b是怎么返回到a的？

**Comment by leeson8888** [comment]
@EHONGYH  可以先判断一下，如果dsBridge 为定义，自己重写一下。给java 中dsBridge注入的代码在js 中重新定义一下。

目前在小米4c，三星部分低端手机(android 5) 等手机上，第一次加载时ok，再次加载时会报dsBridge。
应该是个bug

**Comment by wendux** [comment]
在使用dsBridge之前加一句初始化代码：window._dsbridge&&_dsbridge.init();

**Comment by wendux** [comment]
此问题已修复  #18
