### ISSUE TITLE
Uncaught ReferenceError:Cannot call method 'apply' of undefined at null

### ISSUE THREAD

**Issue by whiskeyfei** [wendux/DSBridge-Android#18]
android 4.2
clone 下来的代码 没动
10-25 11:52:54.063 29187-29187/wendu.jsbdemo E/Web Console: Uncaught ReferenceError: dsBridge is not defined at file:///android_asset/test.html:45

10-25 11:52:54.213 29187-29187/wendu.jsbdemo E/Web Console: Uncaught TypeError: Cannot call method 'apply' of undefined at null:1

可是已经初始化了
 //dsbridge初始化化代码
            window._dsbridge&&_dsbridge.init();

        console.log(dsBridge)
＝＝＝＝＝＝＝＝＝＝＝＝＝＝

这么写dsBridge 是有值的
  function callSyn() {
        console.log(dsBridge)
           alert(dsBridge.call("testSyn", {msg: "testSyn"}))
        }

apply 没定义？谢谢！

注：后来发现在其他设备上是没问题的（新设备是android 5.0），可能和webview内核有关系，还没进一步验证

**Comment by whiskeyfei** [comment]
fixed

**Comment by wendux** [comment]
你是怎么解决的？

**Comment by whiskeyfei** [comment]
https://github.com/whiskeyfei/DSBridge-Android/commit/4fd024340e6dd2a13760fe9145f1c961d11e5ad3    
我的解决方法比较简单直接。就是将register 放入function中执行，不知道你还有没有其他方案

从log来看，在4.2我的设备上发现，还没有等注入完js，test.html 中的js已经往下执行了，所以我的解决方案是，等js完全注入以后，在手动初始化register操作，就是将 register 放入function中执行。

**Comment by wendux** [comment]
```javascript
window._dsbridge&&_dsbridge.init();
console.log(dsBridge)  //这一句有值没？
```

**Comment by whiskeyfei** [comment]
window._dsbridge&&_dsbridge.init();
console.log(dsBridge)  //这一句有值没？ @wendux   这一行没有值，还没等注入完，就已经打印了

**Comment by wendux** [comment]
此问题已修复，详情请参照使用步骤的第三步，在使用`dsBridge`对象之前需要手动初始化一下：
```javascript
//cdn
//<script src="https://unpkg.com/dsbridge/dist/dsbridge.js"> </script>
//npm
//npm install dsbridge
var dsBridge=require("dsbridge")
```
