### ISSUE TITLE
Native调用js未获取到

### ISSUE THREAD

**Issue by hilanmiao** [wendux/DSBridge-Android#19]
demo中addValue为什么没有获取到返回值？而且js加的alert也没有弹呢？

            public void onPageFinished(WebView view, String url) {
                super.onPageFinished(view, url);
                webView.callHandler("addValue", new Object[]{1, "hello"}, new OnReturnValue() {
                    @Override
                    public void onValue(String retValue) {
                        Log.d("jsbridge", "call succeed,return value is " + retValue);
                    }
                });
            }

dsBridge.register('addValue',function(r,l){
        alert('调用goback');
         return r+l;
        })

**Comment by wendux** [comment]
sdk更新后demo没有同步改，现在已修复
