### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jinkailong** [wendux/DSBridge-Android#2]
01-19 17:07:25.993 28912-28912/wendu.jsbdemo E/Web Console: Uncaught ReferenceError: getJsBridge is not defined at file:///android_asset/test.html:42
01-19 17:07:25.993 28912-28927/wendu.jsbdemo D/jsbridge: call succeed,return value is 1hello
01-19 17:08:09.423 28912-28912/wendu.jsbdemo E/Web Console: Uncaught TypeError: Cannot call method 'call' of undefined at file:///android_asset/test.html:46

**Comment by wendux** [comment]
请补充设备信息

**Comment by jinkailong** [comment]
Oppo X9007 android4.3

**Comment by Silnt** [comment]
调用js的方法 js 返回值 必须是字符串吗 如果返回的是 json 就接受不到了

**Comment by wendux** [comment]
@Silnt 约定是字符串，如果是json对象， JSON.stringify(Object)一下就行。

**Comment by wendux** [comment]
@jinkailong 首先：我这边复现不了，这条issue先挂着吧，看还有没有人有这种情况。其次，一个解决方案是你可以将getJsBridge方法的调用时机挪到 dom ready之后。如仍有问题，及时反馈哦。
