### ISSUE TITLE
为什么更改了android的初始化方法呢？

### ISSUE THREAD

**Issue by yikuo123** [wendux/DSBridge-Android#20]
现在ios和android的初始化方法不同，难道在js中还要做区分，分别初始化吗？

**Comment by wendux** [comment]
首先，ios和android不用区分，js在两个平台下初始化方式一致。   添加初始化方法主要是为了解决在有些情况下dsBridge取不到。

**Comment by yikuo123** [comment]
那ios的js需要引入这个npm包吗？引入了会不会出错？android平台确实碰到了获取不到dsBridge的情况

**Comment by wendux** [comment]
可以引也可以不引，但是h5代码应该是同一份代码，为了统一还是引吧，也不大。
