### ISSUE TITLE
WebChromeClient的onProgressChanged无法调用

### ISSUE THREAD

**Issue by skylarliuu** [wendux/DSBridge-Android#23]
webView.setWebChromeClient(new WebChromeClient(){
            @Override
            public void onProgressChanged(WebView view, int newProgress) {
                super.onProgressChanged(view, newProgress);
            }
        });

**Comment by skylarliuu** [comment]
找到问题了。
DWebView：

//    @Override
//    public void setWebChromeClient(WebChromeClient client) {
//        webChromeClient = client;
//    }

    public void setChromeClient(WebChromeClient client){
        webChromeClient = client;
    }

**Comment by wendux** [comment]
并不是`DWebView` 的问题，其中已经做了代理，我在本地测试没有问题。你提供一下细节。
