### ISSUE TITLE
Two functions callback

### ISSUE THREAD

**Issue by revers-back** [wendux/DSBridge-Android#26]
Hello. Is it possible to make async call with 2 callbacks?
```javascript
   function callAsyn() {
            dsBridge.call("testAsyn", {msg: "testAsyn"}, 
		function (v) {
                  alert(v)
	        }, 
		function (v) {
                  promt(v)
              })
    }
```

**Comment by wendux** [comment]
No, one call can only provide one callback.

**Comment by gedw99** [comment]
Maybe you should wait for the first call back and then call the 2nd ?
Is your pipeline requirements sequential or parallel ?

**Comment by revers-back** [comment]
The reaseon this question appears is that some js functions may have two callbacks and we need to delegate this call to native code using dsbridge, for example 
`Samole.JsApi.prototype.getData = function(symbolName, onSymbolResolvedCallback, onResolveErrorCallback) {`
`	this.dsBridge.call("resolveSymbol", {"symbolName": symbolName}, function (v) {`
`  	})`
`};`
It may be  onSymbolResolvedCallback or onResolveErrorCallback per one getData call

**Comment by wendux** [comment]
you can restructure your code like this:

```javascript
dsBridge.call("resolveSymbol", {"symbolName": symbolName}, function (ret) {
  if(ret.error){
     onSymbolResolvedCallback()
  }else{
     onResolveErrorCallback()
  }
})
```
