### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by springuper** [wendux/DSBridge-Android#27]
this is a super simple implementation of js bridge, and our team is very glad to integrate DSBridge to our products, but we also have some concerns and want to patch it to meet those requirements.

so, what's the license of this repo? if it's MIT, that's very helpful.

and, we're happy to contribute back if we think our requirements could benefit others and the patches are works well.

thanks.

**Comment by wendux** [comment]
MIT, and  the IOS version is the same,  I am glad to recieve your PR .

**Comment by wendux** [comment]
DSBridge v3.0 is a milestone version. Compared with v2.0, we have made a lot of changes. Note that v3.0 is incompatible with v2.0, but v2.0 will continue to maintain. If you are a new user, recommend  using v3.0.
