### ISSUE TITLE
Dependency on fly

### ISSUE THREAD

**Issue by gedw99** [wendux/DSBridge-Android#29]
Do I have to use fly like your demo does ? I assume fly is designed to be browser / webview agnostic and that's part of why you wrote it ? Also to make model and browser usage agnostic.

I write all my Js code in golang and transpired into Js and soon WASM and load it into the webview.
I would prefer to not have to write a importer for you fly Js code into my golang code.
But I can if required, hence why I am seeking your advice about fly being needed.

**Comment by wendux** [comment]
no, dsbridge doesn't depend on fly.js .  the demo just  show how dsbridge  work with fly.js .

**Comment by gedw99** [comment]
ok thanks for the confirmation.
wil close...
