### ISSUE TITLE
关于回调的问题，RT

### ISSUE THREAD

**Issue by zhangweicheng2013** [wendux/DSBridge-Android#3]
webView 原生的evaluateJavascript()方法，会有一个回调onReceiveValue来返回结果。但是只是4.4之后的方法，4.4之前用不了。可是在这里面没有找到兼容的方式啊，求解

**Comment by wendux** [comment]
dswebview继承自WebView, 所以4.4之前dswebview也不行。但是，dswebview的callHandler方法允许调用网页中的js函数并获得回调结果，你可以将你要执行的js代码声明一个全局函数在网页中，这样就可以了。
