### ISSUE TITLE
onShowFileChooser 复写问题

### ISSUE THREAD

**Issue by 18649851495** [wendux/DSBridge-Android#30]
为什么onShowFileChooser只写了5.0+版本的，那5.0之前的就不支持了吗

**Comment by wendux** [comment]
此方法是5.0，WebView新添加方法，所以不能在5.0之前使用

**Comment by wendux** [comment]
解决方案请参考 #33

**Comment by 18649851495** [comment]
我自己down了你的源码，结合我自己的业务做了一些处理，另外也处理完了这个问题。谢谢
