### ISSUE TITLE
怎么使用x5内核呢？

### ISSUE THREAD

**Issue by zhonglikui** [wendux/DSBridge-Android#32]
集成X5 SDK的时候需要在Application中 QbSdk.initX5Environment来初始化，这个库不需要吗？
使用x5的时候只需要改compile就可以了吗？layout中还是使用<wendu.dsbridge.DWebView/>吗？
DSBridge-Android:x5-SNAPSHOT也升级3.0版本了吗？

**Comment by wendux** [comment]
请参考x5-3.0分支文档及demo:
https://github.com/wendux/DSBridge-Android/blob/x5-3.0/readme-chs.md
