### ISSUE TITLE
安卓4.4版本，WebChromeClient的openFileChooser方法没有回调

### ISSUE THREAD

**Issue by SAKURA5460** [wendux/DSBridge-Android#33]
public void openFileChooser(ValueCallback<Uri> uploadMsg, String acceptType, String capture) {}

一个简单的 <input type="file"/> 页面。在安卓系统4.4版本，用原生的webview可以响应该方法。DWebview响应不了。控制台输出了这个日志
chromium: [INFO:aw_web_contents_delegate.cc(230)] File Chooser result: mode = 0, file paths =

哥，帮我看看这个啥问题

**Comment by wendux** [comment]
You should implement DWebView.FileChooser interface and override the  openFileChooser of WebChromeClient, as fellows:

``` java
  class MyWebChromeClient extends WebChromeClient implements DWebView.FileChooser{

        @Override
        @TargetApi(Build.VERSION_CODES.HONEYCOMB)
        public void openFileChooser(ValueCallback valueCallback, String acceptType) {
            
        }

        @Override
        @TargetApi(Build.VERSION_CODES.JELLY_BEAN)
        public void openFileChooser(ValueCallback<Uri> valueCallback, String acceptType, String capture) {

        }

        @Override
        @TargetApi(Build.VERSION_CODES.LOLLIPOP)
        public boolean onShowFileChooser(WebView webView, ValueCallback<Uri[]> filePathCallback, FileChooserParams fileChooserParams) {
            //return super.onShowFileChooser(webView, filePathCallback, fileChooserParams);
        }
    }
```

**Comment by SAKURA5460** [comment]
我中文提问的。。你英文回答我。。  不过我看懂啦！现在去试试

**Comment by SAKURA5460** [comment]
找不到这个DWebView.FileChooser接口   我用的是2.0  要升级到3.0对不

**Comment by wendux** [comment]
2.0 has been updated just now, you should rebuild your project and retry。

如果你的APP还未上线，建议使用3.0，如果已有线上版本，那就使用2.0， 2.0刚刚更行了对FileChooser的支持， 重新gradle一下即可。

**Comment by SAKURA5460** [comment]
那2.0还是要实现DWebView.FileChooser吗。
还有 3.0的新方法 addJavascriptObject(Object object, String namespace)  这个namespace是啥参数。"_dsbridge"吗？

**Comment by wendux** [comment]
1 .2.0是要实现DWebView.FileChooser
2. 关于 `addJavascriptObject` 请看3.0文档啊（有中文）

**Comment by SAKURA5460** [comment]
好。已经解决了。谢谢~
