### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by imaiya** [wendux/DSBridge-Android#34]
android端侵入性过大,可以考虑不限定WebView

**Comment by wendux** [comment]
多谢建议，对于这个问题，当初我是这么考虑的：
1. 如果分离，则必会要求用户继承或自己装配我们提供的模块, 对于不同WebView，提供的组件和集成方式还会不一样，这会增加集成成本，提高使用门槛。**这是主要的考虑** 。
2. 目前国内用的最多的第三方WebView为腾讯的X5，DSBridge已提供了X5专版，随着Android系统版本的迭代，原生WebView表现越来越好，APP对第三方WebView的依赖也会越来越少. 基于这些原因DSBridge的覆盖率已经很大。
3. 对于其他的第三方WebView，如crosswalk, 用户可以参照DSBridge源码进行少量修改便可以使用。
