### ISSUE TITLE
dwebView.addJavascriptObject(new JsApi(), null); 没有这个方法

### ISSUE THREAD

**Issue by shuijianbaozi** [wendux/DSBridge-Android#39]
博主这个什么原因造成的

**Comment by shuijianbaozi** [comment]
compile 'com.github.wendux:DSBridge-Android:2.0-SNAPSHOT 使用的是这个library

**Comment by shuijianbaozi** [comment]
OK 我换了library后 setJavascriptInterface()方法失效了,addJavascriptObject()可以使用了,

**Comment by shuijianbaozi** [comment]
博主建议方法名称不要删除,用@Deprecated标注下,

**Comment by wendux** [comment]
3.0和2.0不兼容（关键是原生和js端都不兼容）， 为了不给用户造成一种向下兼容的假象，故直接删除。另外如果你是2.0用户，升级时请考虑是否有旧代码需要兼容，如果有，不建议升级。
