### ISSUE TITLE
加一个列表滑动很卡

### ISSUE THREAD

**Issue by githubchen001** [wendux/DSBridge-Android#4]
首先，此库确实调用方便，很好用，但是遇到一个问题使用dswebview加载一个列表滑动的时候很卡，但是使用原生的webview不会出现这个问题，希望作者优化此处

**Comment by wendux** [comment]
感谢反馈，dswebview是继承自webview, 性能应该没什么差别。会不会是你的列表在滑动的时候频繁调用同步接口导致？同步调用时页面会等待native返回，如果短时间内调用频率太高可能会导致卡顿。如果不是，能否将你的网页源码发给我，我测测。
