### ISSUE TITLE
How to implement DSBridge in existing webview?

### ISSUE THREAD

**Issue by tafelnl** [wendux/DSBridge-Android#40]
Maybe this is a dumb question... But I cannot figure out how to implement this bridge into a already existing WebView. Is it explained somewhere? Is it actually possible? 

Thank you so much in advance for any help you are able to provide!

**Comment by wendux** [comment]
The DWebView  it self  is a subclass of WebView，  you can refer to the implementation source code of the DWebView, and add the  code  in your existing WebView .
