### ISSUE TITLE
The argument of "getXXX" must be a JSON object string

### ISSUE THREAD

**Issue by wjch** [wendux/DSBridge-Android#41]
请问我是按照文档里的java类实现的，为什么会提示这个错误呢，谢谢。

**Comment by wjch** [comment]
打印控制台，显示如下的日志

03-30 13:38:36.818 8735-9117 D/dsBridge: The argument of "getMac" must be a JSON object string!

03-30 13:38:36.818 8735-9117 W/System.err: org.json.JSONException: No value for data

03-30 13:38:36.818 8735-9117 W/System.err:     at org.json.JSONObject.get(JSONObject.java:389)

03-30 13:38:36.818 8735-9117 W/System.err:     at wendu.dsbridge.DWebView$InnerJavascriptInterface.call(DWebView.java:177)
03-30 13:38:36.819 8735-9117 W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-30 13:38:36.819 8735-9117 W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(Unknown Source)
03-30 13:38:36.819 8735-9117 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-30 13:38:36.819 8735-9117 W/System.err:     at android.os.Looper.loop(Looper.java:163)
03-30 13:38:36.819 8735-9117 W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by wendux** [comment]
看一下你的dsbridge.js版本是不是对的
