### ISSUE TITLE
急急急！！！给JS回调结果时出现的异常

### ISSUE THREAD

**Issue by oywjAndroid** [wendux/DSBridge-Android#42]
在Android4.2.2版本的机器上，js调用本地Java代码之后给js回调返回值的时候出现了："Uncaught SyntaxError: Invalid or unexpected token", source:  (1)异常，但是在Android4.4版本上不会出现这个异常。

**Comment by oywjAndroid** [comment]
这是我的代码：
@JavascriptInterface
    public void generateQRCode(JSONObject requestParams, CompletionHandler handler) {
        try {
            String url = requestParams.getString("url");
            Log.i(TAG,"JS请求二维码:"+url);

            // 1.生成二维码图片
            MultiFormatWriter multiFormatWriter = new MultiFormatWriter();
            BitMatrix result = multiFormatWriter.encode(url, BarcodeFormat.QR_CODE, 300, 300);
            BarcodeEncoder barcodeEncoder = new BarcodeEncoder();
            Bitmap bitmap = barcodeEncoder.createBitmap(result);

            // 2.将二维码图片转成Base64的字符串
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, byteArrayOutputStream);
            byte[] imageBytes = byteArrayOutputStream.toByteArray();
            String qrImage = Base64.encodeToString(imageBytes, Base64.DEFAULT);

            // 3.回调给JS
            Log.d(TAG,qrImage);
            handler.complete(qrImage);
        } catch (JSONException | WriterException e) {
            e.printStackTrace();
        }
    }

**Comment by wendux** [comment]
请贴出错误内容的详细信息，就是"Uncaught SyntaxError: Invalid or unexpected token"附近的
