### ISSUE TITLE
Json接收数据反斜杠转换问题

### ISSUE THREAD

**Issue by LiuBeixi** [wendux/DSBridge-Android#43]
您好！我想问下，如果是回传的json的话 我Android这边接收到的url连接的“/”会变成“\/”,这个是什么问题呢？我先暂时只能用url的encode和decode来解决

**Comment by LiuBeixi** [comment]
哦哦～确实是这样子，目前还碰到一个问题，我前段用的vue的框架，引入DSBridge之后在客户端webview中加载特别慢，一个简单demo测试页加载将近10来秒，以前用的是原生的方法，为了统一引用了DSBridge，这个得怎么优化？盼复～

**Comment by wendux** [comment]
不要用cdn引入dsbridge.js ，npm 的cdn 本来就慢，可以考虑下载引入，或使用npm 安装到本地
