### ISSUE TITLE
js调用原生方法的问题

### ISSUE THREAD

**Issue by XiaYL** [wendux/DSBridge-Android#45]
目前发现两个问题：
1）dsbridge.js在定义call方法的时候，如果入参是number类型的0，会导致结果data是空json，而不是0
![z h eijcf d 4wdg 4opt](https://user-images.githubusercontent.com/15325562/38670296-f21c428e-3e7a-11e8-8d38-98c41dc77d70.png)
原先的这个方法，在入参是number 0 的时候，直接是false了，这样就出错了

2）DWebView的InnerJavascriptInterface里面的call方法，在获取方法的时候，考虑到继承相关的问题，应该使用getMethod，不是getDeclaredMethod

**Comment by wendux** [comment]
已修复，请升级dsbridge.js 到3.1.1， 并重新构建Android工程
