### ISSUE TITLE
同步只是针对H5调原生吗？

### ISSUE THREAD

**Issue by jonenet** [wendux/DSBridge-Android#47]
同步和异步只针对H5的吗？
因为我看Java中始终是在异步线程回调的

**Comment by wendux** [comment]
对的，因为：
1. webview调用javaScript的前提条件是javascript context已经建立，我们在原生代码调用可能发生在任何时候，这也就意味着原生调用h5的大所述场景都是异步的。
2. 目前webview没有提供任何同步调用javaScript的办法，即使调用`loadUrl`，也不是同步的。

**Comment by mrrobot97** [comment]
关于native同步调用js，这种方法是否可以作为参考呢？
https://github.com/gcesarmza/androidSamples/blob/master/webview/src/main/java/com/gustavogenovese/webview/SynchronousJavascriptInterface.java
