### ISSUE TITLE
在Android 4.4 里面 反射代理对象的时候，拿不到已注册的方法

### ISSUE THREAD

**Issue by hui453694187** [wendux/DSBridge-Android#48]
Object jsb = DWebView.this.javaScriptNamespaceInterfaces.get(nameStr[0]);

这个拿到设置的对象了，但是 
jsb.getClass().getMethods(); 里面没有已设置对象对应的函数 
报 错 ，“Not find method  methodName implementation! please check if the  signature or namespace of the method is right ”

  在 7.0 的系统里面就是正常的 。  

这个是bug 么？

**Comment by hui453694187** [comment]
原因是 代理对象 的  函数， 需要申明是  public  的 方法，  在4.4 的系统 如果不是 public 的 反射执行方法是，会报找不到方法名。

还有一个问题就是， dsbridge 的初始化， 影响了页面的渲染速度， 导致页面打开很慢， 加载速度大大降低， 请问作者有什么办法解决么？

**Comment by wendux** [comment]
通过npm 安装dsbridge.js或将其下载到你的h5 工程  unpkg 的cdn 比较慢

**Comment by hui453694187** [comment]
你好， 我指的并不是 加载js慢， 而已  调用 _dsbridge init() 方法  有点慢，导致加载速度慢了

**Comment by wendux** [comment]
这个方法应该不会太慢，一次js调用原生而已，你有性能分析的数据吗？
