### ISSUE TITLE
建议想办法吧webview耦合抽离出来

### ISSUE THREAD

**Issue by wlfcolin** [wendux/DSBridge-Android#5]
建议把webview耦合部分抽离出来，因为有些项目很可能需要第三方webview组件，比如crosswalk，腾讯X5等

**Comment by wendux** [comment]
首先，多谢建议。其实dsbridge刚开始时是同时支持crosswalk和x5的，最后考虑到一下几点原因取掉了：
1.  Android 版本更新很快，自带webview能力越来越强，一般app对第三方浏览器内核需求越来越小［主要原因］。
2. 若支持crosswalk和x5，工程中就必然要引入这两者的jar包和lib库，这会让不需要这两者的开发者手动剥离，会增加集成成本。
3. 如果要使用crosswalk和x5，可以仿照源码中webview的实现方式，原理很像，（ps:需要注意的是crosswalk中@javascript标注和webview中的同名不同包，引入错了会导致接口执行不了）。

因为dsbridge的实现原理是侵入式的，需要在webview加载页面的过程中执行一些操作，所以无法隔离.
