### ISSUE TITLE
Not find method "" + methodName + "" implementation! please check if the  signature or namespace of the method is right

### ISSUE THREAD

**Issue by hrx3627** [wendux/DSBridge-Android#52]
Not find method "" + methodName + "" implementation! please check if the  signature or namespace of the method is right

大神，你好。我在使用你的库的时候，这个通过反射获取方法是空的，我的方法修饰符是public，请问是什么原因呢？

**Comment by wendux** [comment]
把你代码贴出来

**Comment by wendux** [comment]
长时间未回复，先关闭。

**Comment by zhangyubao** [comment]
Resolve it.
@JavascriptInterface
fun sendInvitation(friendData: Any){
RxBus.post(EventSendIM(friendData))
}

函数中定义的方法一定要是Object类型
