### ISSUE TITLE
X5 WebView内存泄露

### ISSUE THREAD

**Issue by 1690251766** [wendux/DSBridge-Android#54]
平台：Android

version: x5-3.0

描述：引入X5 WebView的DWebView页面发生内存泄露。

问题复现：
目前发现两处内存泄露，
a:MainActivity，点击返回键回到桌面发生内存泄露；
b:其他页面，销毁时发生内存泄露；

附上内存泄露截图（内存泄露工具：https://github.com/square/leakcanary）

![qq 20180621155800](https://user-images.githubusercontent.com/11400746/41705663-3a688a2a-756c-11e8-8387-0d33ba5041a6.png)
![qq 20180621155710](https://user-images.githubusercontent.com/11400746/41705670-3f96ab26-756c-11e8-82d5-0d3987f7395b.png)

这是一个非常好的工具，解决了Android和iOS的一致性问题，并且提供了X5 WebView，解决了兼容性问题，点个大大的赞！

**Comment by LinhaiGu** [comment]
我也一样，我这边都没有load，就在 xml引入控件就不停的GC，造成内存泄露

**Comment by 1690251766** [comment]
嗯，得在看看

**Comment by wendux** [comment]
@1690251766  你页面消毁时有没有调用webview的destory方法？

**Comment by louis2610** [comment]
页面消毁时调用了webview的destory方法也不管用，还是内存泄漏
