### ISSUE TITLE
View.post(Runnable) will cause memory leak

### ISSUE THREAD

**Issue by wlfcolin** [wendux/DSBridge-Android#6]
there are some memory leaks in DWebView class
// line 618
  public void loadUrl(final String url, final Map<String, String> additionalHttpHeaders) {
        **post(new Runnable() {
            @Override
            public void run() {
                DWebView.super.loadUrl(url, additionalHttpHeaders);
            }
        });**
    }
// line 592
  public void loadUrl(final String url) {
        **post(new Runnable() {
            @Override
            public void run() {
                DWebView.super.loadUrl(url);
            }
        });**
    }
// line 534
   public void evaluateJavascript(final String script) {
        if (Looper.getMainLooper() == Looper.myLooper()) {
            _evaluateJavascript(script);
        } else {
            **post(new Runnable() {
                @Override
                public void run() {
                    _evaluateJavascript(script);
                }
            });**
        }
    }
, which will cause serious crash(java.lang.OutOfMemoryError), i recommend that you should use the [WeakHandler.post(Runnable)](https://github.com/badoo/android-weak-handler)  instead of using View.post(Runnable)

**Comment by leeson8888** [comment]
really crashed often

**Comment by wendux** [comment]
fixed
