### ISSUE TITLE
Is it possible pass Native class object to js ?

### ISSUE THREAD

**Issue by mksantoki** [wendux/DSBridge-Android#61]
I added description here below link

https://stackoverflow.com/questions/51481575/web-apps-in-webview-android

**Comment by mksantoki** [comment]
https://stackoverflow.com/questions/51481575/web-apps-in-webview-android

**Comment by buhe** [comment]
You can convert object to json

**Comment by mksantoki** [comment]
Thank you for your response. Can you please help how to convert netive
class object to json native class example like database class.

**Comment by wendux** [comment]
@mksantoki  As @buhe says， you should convert Java object to json to pass。
