### ISSUE TITLE
 Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by JoeysWang** [wendux/DSBridge-Android#67]
我直接把https://unpkg.com/dsbridge@3.1.3/dist/dsbridge.js 这里的代码放到<script>标签内，
然后在下一行调用  var dsBridge = require("dsbridge");
就报 Uncaught ReferenceError: require is not defined

**Comment by wendux** [comment]
你如果要使用CDN方式引入的话，通过<script>标签引入后直接就可以使用`dsBridge`对象。require是npm方式引入。

**Comment by xiaozuopeng** [comment]
直接使用也会报错
Uncaught ReferenceError: module is not defined at dsbridge.js:4

**Comment by wendux** [comment]
这个错误不影响，忽略就行, 或者你可以使用3.1.4
