### ISSUE TITLE
新发布的版本有问题

### ISSUE THREAD

**Issue by HelkeNarmo** [wendux/DSBridge-Android#68]
DWebView里的callHandler，原来的this.callID++改成了++this.CallID,导致返回值找不到。

**Comment by wendux** [comment]
@HelkeNarmo 嗯，3.0分支已经修复，还没有合入到主分支，如果着急，可以在gradle中依赖3.0分支，我会在今天晚上将修改合入到主分支


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by wendux** [comment]
已合入
