### ISSUE TITLE
小米 第一次加载崩溃

### ISSUE THREAD

**Issue by wanglyGithub** [wendux/DSBridge-Android#73]
09-10 14:45:00.766 14062-14062  art: art/runtime/java_vm_ext.cc:410]   at java.lang.Object java.lang.reflect.Constructor.newInstance!(java.lang.Object[]) (Constructor.java:-2)
09-10 14:45:00.766 14062-14062/ at void com.tencent.smtt.sdk.QbSdk.loadTBSSDKExtension(android.content.Context, java.lang.String) ((null):-1)
09-10 14:45:00.766 14062-14062/ at boolean com.tencent.smtt.sdk.QbSdk.canLoadX5FirstTimeThirdApp(android.content.Context) ((null):-1)
09-10 14:45:00.766 14062-14062/  at void com.tencent.smtt.sdk.TbsShareManager.forceToLoadX5ForThirdApp(android.content.Context, boolean) ((null):-1)
09-10 14:45:00.766 14062-14062/ art/runtime/java_vm_ext.cc:410]   at void com.tencent.smtt.sdk.o.b(android.content.Context, boolean, boolean) ((null):-1)
09-10 14:45:00.766 14062-14062/  at void com.tencent.smtt.sdk.bt.a(android.content.Context) ((null):-1)
09-10 14:45:00.766 14062-14062/  at void com.tencent.smtt.sdk.WebView.c(android.content.Context) ((null):-1)
09-10 14:45:00.766 14062-14062/   at void com.tencent.smtt.sdk.WebView.<init>(android.content.Context, android.util.AttributeSet, int, java.util.Map, boolean) ((null):-1)
09-10 14:45:00.766 14062-14062/  at void com.tencent.smtt.sdk.WebView.<init>(android.content.Context, android.util.AttributeSet, int, boolean) ((null):-1)
09-10 14:45:00.766 14062-14062/  at void com.tencent.smtt.sdk.WebView.<init>(android.content.Context, android.util.AttributeSet, int) ((null):-1)
09-10 14:45:00.766 14062-14062/  at void com.tencent.smtt.sdk.WebView.<init>(android.content.Context, android.util.AttributeSet) ((null):-1)
09-10 14:45:00.766 14062-14062/  at void wendu.dsbridge.DWebView.<init>(android.content.Context, android.util.AttributeSet) (DWebView.java:226)
09-10 14:45:00.766 14062-14062/  at void com.superwebview.utils.X5WebView.<init>(android.content.Context, android.util.AttributeSet) (X5WebView.java:0)

**Comment by wendux** [comment]
有关x5初始化和添加so库(如果需要)等参照x5官网。dsbridge 只是集成了sdk，初始化还得开发者自己做。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
