### ISSUE TITLE
"Uncaught ReferenceError: dsBridge is not defined", source: file:///android_asset/js-call-native.html

### ISSUE THREAD

**Issue by skybebe** [wendux/DSBridge-Android#74]
运行demo，log如题

**Comment by wendux** [comment]
@skybebe 你运行的设备需要联网，因为demo js初始化是通过cdn引入的dsbridge


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by skybebe** [comment]
有联网呀的，而且我试着用android将js注入webview的方式也不行

**Comment by wendux** [comment]
@skybebe 主页的issue只会显示你自己项目的issue, 你有一年内有提过issue的项目吗。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by skybebe** [comment]
肯定有啊，你什么意思

**Comment by wendux** [comment]
@skybebe 就是你自己的项目下，一年内提的issue才会显示。我刚看了一下你的主页，你项目中唯一有的一条issue是一年前提的，所以才会是空的。你给其它项目提的issue是不会在主页显示的,github API有限制。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by skybebe** [comment]
> @skybebe 就是你自己的项目下，一年内提的issue才会显示。我刚看了一下你的主页，你项目中唯一有的一条issue是一年前提的，所以才会是空的。你给其它项目提的issue是不会在主页显示的,github API有限制。
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

1.其他项目的issue跟这个issue有什么直接关系？请回答此issue问题
2.我就今年提的issue多，我猜你只能看到一年前的
3.所有open的issue都会在主页显示

**Comment by wendux** [comment]
@skybebe 尴尬了，回错issue了，看成另外一个项目嗯了，浏览器窗口开的多了……😅。  这个错误就是dsbridge.js 没有引入成功，如果你确定你的设备网络没有问题，可以把这个js内容粘贴到html标签中试试，Demo你如果没有修改过的话，我这边测过好多机器，没遇到过问题，对了，你是用的3.x吗？


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
