### ISSUE TITLE
调用callHandler传入String类型的数据显示的字段为空，不知道你们遇到过没有是怎么解决的

### ISSUE THREAD

**Issue by ptrtony** [wendux/DSBridge-Android#78]
mWVJBWebView.callHandler("pickLot", carPortBean, new WVJBWebView.WVJBResponseCallback<CarPortBean>() {

                    @Override
                    public void onResult(CarPortBean carPortBean) {
                        ToastManager.getInstance(getApplicationContext()).showText(carPortBean.lotNo);
                    }
                });

**Comment by wendux** [comment]
你这使用的不是DSBridge，提错位置了吧
