### ISSUE TITLE
call()函数返回值

### ISSUE THREAD

**Issue by XingshengLiu** [wendux/DSBridge-Android#8]
@wendux 你好！DWebView中的call方法返回的是String，需要需要返回Map<>，在DWebView中重写了一个callObject方法，大体原先的call（）方法差不多，把返回的object转换成了map返回，在injectJs（）中，仿照原先的注入方法，加上了一段新的js脚本，但是这样调用不到？可以指导一下思路吗？

**Comment by wendux** [comment]
建议是在需要map时，返回一个map的json字符串，在json中通过JSON.parse()转化成json对象

**Comment by XingshengLiu** [comment]
就是把之前返回的object进行一下转换是吗？

**Comment by XingshengLiu** [comment]
@wendux 还要请教一下，在WEbView中有private static final String BRIDGE_NAME = "_dsbridge"; 这个变量，在注入的那段js代码中也有_dsbridge，想问下_dsbridge的作用是什么呢？

**Comment by wendux** [comment]
JavaScript  object 真正的对象名，详情请参考webview addJavascriptInterface
