### ISSUE TITLE
按照文档js调用java方法没反应

### ISSUE THREAD

**Issue by jaysowen** [wendux/DSBridge-Android#81]
按照例子接入的,然后开启了调试模式,发现js调用java方法,然后java这边没有回调反应
报错提示:
Not find method "testSyn" + methodName + "" implementation! please check if the signature or namespace of the method is right.

配置如下:
implementation 'com.github.wendux:DSBridge-Android:master-SNAPSHOT'

代码如下:
`@Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        DWebView.setWebContentsDebuggingEnabled(true);
        dWebView.setWebViewClient(new WebViewClient() {

            // Handle API until level 21
            @SuppressWarnings("deprecation")
            @Override
            public WebResourceResponse shouldInterceptRequest(WebView view, String url) {

                return getNewResponse(url);
            }

            // Handle API 21+
            @TargetApi(Build.VERSION_CODES.LOLLIPOP)
            @Override
            public WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request) {

                String url = request.getUrl().toString();

                return getNewResponse(url);
            }

            private WebResourceResponse getNewResponse(String url) {

                try {
                    OkHttpClient httpClient = new OkHttpClient();

                    Request request = new Request.Builder()
                            .url(url.trim())
                            .addHeader("Authorization", SettingUtil.getInstance().getToken(AppContext.getContext())) // Example header
                       
                    Response response = httpClient.newCall(request).execute();

                    return new WebResourceResponse(
                            null,
                            response.header("content-encoding", "utf-8"),
                            response.body().byteStream()
                    );

                } catch (Exception e) {
                    return null;
                }

            }
        });
        initWebView();
        String finalUrl = handleUrl();
        dWebView.addJavascriptObject(new JsApi(), null);
        dWebView.loadUrl(finalUrl);
    }

    private void initWebView() {
        dWebView.getSettings().setJavaScriptEnabled(true);
        dWebView.getSettings().setRenderPriority(WebSettings.RenderPriority.HIGH);
        dWebView.getSettings().setCacheMode(WebSettings.LOAD_DEFAULT);  //设置 缓存模式
        // 开启 DOM storage API 功能
        dWebView.getSettings().setDomStorageEnabled(true);
        //开启 database storage API 功能
        dWebView.getSettings().setDatabaseEnabled(true);
        //开启 Application Caches 功能
        dWebView.getSettings().setAppCacheEnabled(false);
    }`

**Comment by jaysowen** [comment]
JS写错了,打扰了

**Comment by is1988** [comment]
HAHA Excuse me
