### ISSUE TITLE
请问一下，兼容marcuswestin/WebViewJavascriptBridge

### ISSUE THREAD

**Issue by feer921** [wendux/DSBridge-Android#82]
是否兼容这个库？marcuswestin/WebViewJavascriptBridge

如果不兼容，是否意味着，前端工程师要按你的库的示例来写js代码？

**Comment by wendux** [comment]
不兼容，它们的协议不一样。https://github.com/wendux/WebViewJavascriptBridge 这个兼容，但已经停止维护了，你可以参考一下。
