### ISSUE TITLE
Demo里面fly.js test两个按钮点击无反应

### ISSUE THREAD

**Issue by is1988** [wendux/DSBridge-Android#85]
Demo首页第三个Work with fly.js test进入后，访问baidu以及展示github img这两个方法点击无效，刚开始以为是网络问题，把下面三个引用下载到本地尝试依旧无效，请问是我哪里配置有问题吗？
```
    <!--require dsbridge init js-->
    <script src="https://cdn.jsdelivr.net/npm/dsbridge@3.1.3/dist/dsbridge.js"> </script>
    <!--require flyio-->
    <script src="https://cdn.jsdelivr.net/npm/flyio/dist/fly.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flyio/dist/engine-wrapper.min.js"></script>
```

**Comment by is1988** [comment]
手上两个小米手机 分别是小米note（6.0.1）和小米6x（8.1.0）

**Comment by wendux** [comment]
demo的代码你没有任何改动吧？

**Comment by is1988** [comment]
没有做改动  就是fly.js的页面没有响应  其他都是正常

**Comment by paperscz** [comment]
确实点了没反应

**Comment by wendux** [comment]
@is1988 @paperscz 难道是jsdelivr的cdn在有些地区访问不了？可以试试这个链接能不能打开https://cdn.jsdelivr.net/npm/flyio/dist/fly.min.js

**Comment by is1988** [comment]
@wendux 这个连接可以打开 之前我也怕是cdn的问题 我已经把fly.js下载到本地去引用
还是没反应 最后就是用jquery的ajax来请求了 
只做了android 把hybird的H5搬过来复用 架子还是原生 目前还未发现不能解决的问题
看后期接入iOS的时候 是否正常 因为自己对iOS了解不是很深 还不清楚哪些功能放在H5
哪些放在原生  走一步算一步 至少可以让H5前端开发帮我画页面啦  嘿嘿嘿~

**Comment by paperscz** [comment]
我本地已经调通了，主要适合fly.js里面adapter的dsbridge是一个adapter，不是这个库asserts里面的dsbridge，尽管同名，然后这个fly和adapter的版本好像不对，我换了几下。。可以了。。。看js代码能看出哪里有问题
