### ISSUE TITLE
华为手机上面 X5内核加载失败

### ISSUE THREAD

**Issue by JunFreeman** [wendux/DSBridge-Android#86]
DSBridge的demo在华为的机器上面 加载X5内核是失败的。
 IX5WebViewExtension x5WebViewExtension = dWebView.getX5WebViewExtension();
x5WebViewExtension是null。并且load官方的URL：http://soft.imtt.qq.com/browser/tes/feedback.html。显示的也是00000。手机上有安装QQ 微信的。

**Comment by JunFreeman** [comment]
![image](https://user-images.githubusercontent.com/14955364/49070472-b447f200-f266-11e8-90d1-cae6f7466b7b.png)

为啥DS里面 没有X5官方demo里面的这个so库啊

**Comment by wendux** [comment]
这个x5官方貌似有解释，https://x5.tencent.com/tbs/technical.html#/detail/sdk/1/34cf1488-7dc2-41ca-a77f-0014112bcab7
